### ISSUE TITLE
There's no secret.py in settings

### ISSUE THREAD

**Issue by cheremovsky** [trimailov/finance#1]
Hi there!
I get an error "from finance.settings import secret",
and it's unsurprisingly, there's no secret.py in settings directory.
Am I supposed to create it by myself and figure out which vars I should keep there?

**Comment by trimailov** [comment]
Hi, I have never though someone will use this personal project. :)

Yes, `secret.py` is not in git on purpose and must be created by yourself.

Just add setting there which need to be secret, e.g. I have these:

```
# most important
SECRET_KEY
# others are non vital.
EMAIL_HOST_PASSWORD
OPBEAT
POSTMARK_API_KEY
```

_I should probably create `secret.py.example` :/_

**Comment by cheremovsky** [comment]
Hah, well, you never know)
Yeah, I got it running, thanks.

Another question: in dev setting pages load extremely slow, like 3-4 secs for a page. What could I do with that?

**Comment by trimailov** [comment]
On dev settings with debug toolbars and so on, the app will always run a bit slower.

Though it depends on how you run it. If you run it through vagrant - it will work even slower, especially to reload. Though I do not think so that it should load a page for 3-4 seconds.
